apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: appsdata-api
    environment: dev
  name: appsdata-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsdata-api
      environment: dev
  template:
    metadata:
      labels:
        app: appsdata-api
        environment: dev
    spec:
      containers:
      - image: akskh01acr.azurecr.io/appsdata/api:v1
        name: appsdata-api
        imagePullPolicy: Always
        env:
        - name: APP_HOST
          value: appsdata20220401pgsqlsvr.postgres.database.azure.com
        - name: APP_USER
          value: myadmin
        - name: APP_PASSWORD
          value: 
        - name: APP_DB
          value: tutorials
        - name: APP_DIALECT
          value: postgres
        ports:
        - name: http
          containerPort: 8080
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "250Mi"
            cpu: "250m"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: appsdata-api
    environment: dev
  name: appsdata-api-svc
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    protocol: TCP
    port: 80
    targetPort: 8080
  selector:
    app: appsdata-api
    environment: dev
