apiVersion: v1
kind: ConfigMap
metadata:
  namespace: default
  name: config
data:
  config.js: |-
      const config = (() => {
          return {
            "VUE_APP_APIURL": "http://localhost:8080/api/",
          };
        })();
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  labels:
    app: appsdata-ui
    environment: dev
  name: appsdata-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsdata-ui
      environment: dev
  template:
    metadata:
      labels:
        app: appsdata-ui
        environment: dev
    spec:
      containers:
      - image: akskh01acr.azurecr.io/appsdata/ui:v1
        name: appsdata-ui
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 80
        resources:
          requests:
            memory: "250Mi"
            cpu: "250m"
          limits:
            memory: "250Mi"
            cpu: "250m"
        volumeMounts:
        - name: config-js
          mountPath: /usr/share/nginx/html/config.js
          subPath: config.js
      restartPolicy: Always
      volumes:
      - name: config-js
        configMap:
          name: config
          items:
            - key: config.js
              path: config.js
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  labels:
    app: appsdata-ui
    environment: dev
  name: appsdata-ui-svc
spec:
  type: LoadBalancer
  ports:
  - name: "http"
    protocol: TCP
    port: 80
    targetPort: 80
  selector:
    app: appsdata-ui
    environment: dev
